package com.tdubuis.deltaforceapi.entity.redItem;

public enum RedItemType
{
	PRODUIT_ELECTIONIQUE,
	OBJET_MEDICAL,
	OUTIL_ET_MATERIAU,
	OBJET_MENAGER,
	FABRICATION,
	RENSEIGNEMENTS,
	COMBUSTIBLE_ENERGETIQUE,
	OBJET_DE_VALEUR,
	EXCLUSIVITE_DE_LA_SAISON
}
